"""create account table

Revision ID: 169aee50c7ac
Revises: 749177b71249
Create Date: 2022-11-24 14:04:17.913229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '169aee50c7ac'
down_revision = '749177b71249'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner', sa.Column('banner_order', sa.Integer(), nullable=True))
    op.drop_index('ix_banner_banner position', table_name='banner')
    op.create_index(op.f('ix_banner_banner_order'), 'banner', ['banner_order'], unique=False)
    op.drop_column('banner', 'banner position')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner', sa.Column('banner position', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_banner_banner_order'), table_name='banner')
    op.create_index('ix_banner_banner position', 'banner', ['banner position'], unique=False)
    op.drop_column('banner', 'banner_order')
    # ### end Alembic commands ###
