"""add restaurant menu items

Revision ID: 749177b71249
Revises: dcfbb937dbb9
Create Date: 2022-11-09 13:55:12.538700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '749177b71249'
down_revision = 'dcfbb937dbb9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_menu_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Product available in menu', sa.Boolean(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurant_menu_item_id'), 'restaurant_menu_item', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restaurant_menu_item_id'), table_name='restaurant_menu_item')
    op.drop_table('restaurant_menu_item')
    # ### end Alembic commands ###
