"""Remove verbose name from all models

Revision ID: 8e1a8092c5b4
Revises: d59ef26a67bd
Create Date: 2022-12-06 15:00:17.122535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e1a8092c5b4'
down_revision = 'd59ef26a67bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_category', sa.Column('title', sa.String(length=100), nullable=True))
    op.drop_column('products_category', 'Product category title')
    op.add_column('restaurant', sa.Column('title', sa.String(length=100), nullable=True))
    op.add_column('restaurant', sa.Column('contact_phone', sa.String(length=50), nullable=True))
    op.drop_column('restaurant', 'Restaurant title')
    op.drop_column('restaurant', 'Contact phone')
    op.add_column('restaurant_menu_item', sa.Column('available', sa.Boolean(), nullable=True))
    op.drop_column('restaurant_menu_item', 'Product available in menu')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_menu_item', sa.Column('Product available in menu', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('restaurant_menu_item', 'available')
    op.add_column('restaurant', sa.Column('Contact phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('restaurant', sa.Column('Restaurant title', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('restaurant', 'contact_phone')
    op.drop_column('restaurant', 'title')
    op.add_column('products_category', sa.Column('Product category title', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('products_category', 'title')
    # ### end Alembic commands ###
