"""create tables

Revision ID: a4d974fdea33
Revises: 
Create Date: 2022-10-19 23:25:34.781067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d974fdea33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('banner position', sa.Integer(), nullable=True),
    sa.Column('image_file', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banner_banner position'), 'banner', ['banner position'], unique=False)
    op.create_index(op.f('ix_banner_id'), 'banner', ['id'], unique=False)
    op.create_index(op.f('ix_banner_title'), 'banner', ['title'], unique=False)
    op.create_table('restaurant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Restaurant title', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('Contact phone', sa.String(length=50), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurant_id'), 'restaurant', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restaurant_id'), table_name='restaurant')
    op.drop_table('restaurant')
    op.drop_index(op.f('ix_banner_title'), table_name='banner')
    op.drop_index(op.f('ix_banner_id'), table_name='banner')
    op.drop_index(op.f('ix_banner_banner position'), table_name='banner')
    op.drop_table('banner')
    # ### end Alembic commands ###
