"""add_image_field

Revision ID: a699779454fd
Revises: b8804be70219
Create Date: 2022-10-15 23:41:39.917370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a699779454fd'
down_revision = 'b8804be70219'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner', sa.Column('image_file', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banner', 'image_file')
    # ### end Alembic commands ###
