"""Remove verbose name

Revision ID: d59ef26a67bd
Revises: 169aee50c7ac
Create Date: 2022-12-06 14:56:30.798334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd59ef26a67bd'
down_revision = '169aee50c7ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('title', sa.String(length=100), nullable=True))
    op.add_column('product', sa.Column('price', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('product', sa.Column('image_url', sa.String(length=100), nullable=True))
    op.add_column('product', sa.Column('special_status', sa.Boolean(), nullable=True))
    op.drop_index('ix_product_Special status', table_name='product')
    op.create_index(op.f('ix_product_special_status'), 'product', ['special_status'], unique=False)
    op.drop_column('product', 'Special status')
    op.drop_column('product', 'Product title')
    op.drop_column('product', 'Product image url')
    op.drop_column('product', 'Product price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('Product price', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('Product image url', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('Product title', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('Special status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_product_special_status'), table_name='product')
    op.create_index('ix_product_Special status', 'product', ['Special status'], unique=False)
    op.drop_column('product', 'special_status')
    op.drop_column('product', 'image_url')
    op.drop_column('product', 'price')
    op.drop_column('product', 'title')
    # ### end Alembic commands ###
