"""app product model

Revision ID: dcfbb937dbb9
Revises: a4d974fdea33
Create Date: 2022-10-19 23:53:44.165448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcfbb937dbb9'
down_revision = 'a4d974fdea33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Product category title', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category_id'), 'products_category', ['id'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Product title', sa.String(length=100), nullable=True),
    sa.Column('Product price', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('Product image url', sa.String(length=100), nullable=True),
    sa.Column('Special status', sa.Boolean(), nullable=True),
    sa.Column('ingredients', sa.String(length=200), nullable=True),
    sa.Column('product_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_category_id'], ['products_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_Special status'), 'product', ['Special status'], unique=False)
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_index(op.f('ix_product_Special status'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_products_category_id'), table_name='products_category')
    op.drop_table('products_category')
    # ### end Alembic commands ###
